### ISSUE TITLE
Blurry camera on an iphone

### ISSUE THREAD

**Issue by Thormeard** [mat2718/vision-camera-mrz-scanner#2]
Hi!
Im trying to use your plugin and I have very blurry camera (like resolution is set to 400x200 or something) on iphone (x and 13). I managed to fix the camera by changing this line https://github.com/mat2718/vision-camera-mrz-scanner/blob/main/src/components/MRZCamera.tsx#L251 
from `format={cameraProps?.format ?? format}`
to `format={cameraProps?.format ?? undefined}`
But then it cannot detect anything. Hold still message blinking and nothing happens. (may be related to the format may be separate problem)
Same problem with example app.
Works fine on my colleague's android device.

Is possible that you can test it out on an iphone? Let me know if you need some additional information. Would be happy to help.
Thanks!

**Comment by mat2718** [comment]
if you get a chance. can i get you to load the most recent version of the library to see if this is still an issue

**Comment by Thormeard** [comment]
Tried last version - fixed!
Thank you!
